import Head from 'next/head'
import Navbar from '../components/Navbar'
import BottomNav from '../components/BottomNav'

export default function Home() {
    return (
        <div className="bg-[#EAEDED]">
            <Head>
                <title>Amazon</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <Navbar />
                <BottomNav />
            </div>
        </div>
    )
}
