import Head from 'next/head'
import Navbar from '../components/Navbar'
import Banner from '../components/Banner'
import HomePage from '../components/HomePage'
import BottomNav from '../components/BottomNav'

export default function Home({ results }) {
    return (
        <div className="bg-[#EAEDED] min-h-screen">
            <Head>
                <title>Amazon</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <Navbar />
                <BottomNav />
                <Banner />
                <HomePage results={results} />
            </div>
        </div>
    )
}

export async function getServerSideProps(context) {
    let data = []
    const request = await fetch('https://fakestoreapi.com/products')
        .then((res) => res.json())
        .then((res) => (data = res))

    return {
        props: {
            results: data,
        },
    }
}
